### ISSUE TITLE
8.1 HW #5-8

### ISSUE THREAD

**Issue by imasaru** [byoshiwara/mfg#12]
It looks like things went a bit wonky here:

![image](https://user-images.githubusercontent.com/10376491/49719385-985b2d80-fc22-11e8-8332-0b03189eafbd.png)

The numbering is off and the problems seem to be misaligned.

**Comment by imasaru** [comment]
The error found its way into the answer key as well:

![image](https://user-images.githubusercontent.com/10376491/49719523-069ff000-fc23-11e8-986b-0c02f8f3571e.png)

**Comment by byoshiwara** [comment]
Thanks.

My numbering error is fixed, but changes won't show up in the online version being used. (We are making corrections in the "version" branch, and will probably put up a corrected book during summer 2019.)

The alignment issue arises from how PreTeXt created the html document(s). I'm not sure when (or if) that will be fixed.

Cheers.

Bruce Yoshiwara

----------------------------------------------------------------------
byoshiwara@hotmail.com<mailto:byoshiwara@hotmail.com>
Twitter: @byoshiwara
Blog: http://byoshiwara.blogspot.com/
Webpage: https://byoshiwara.github.io
I'm hoping to be a late bloomer.

----------------------------------------------------------------------

________________________________
